### ISSUE TITLE
Updates needed for Monolog

### ISSUE THREAD

**Issue by MikeDevs** [shipperhq/module-logger#3]
It looks like the new version of Monolog coming in with Magento 2.4.4 is going to require some updates to module-logger. It is currently throwing errors in the CLI, frontend, and backend of Magento 2.4.4. 

Specifically the Logger model class extending `\Monolog\Logger` will need to be updated to return void instead of Boolean on log calls. Happy to submit a PR if needed, just lmk.

**Comment by ibraheemnabeelfauzi** [comment]
Hey @MikeDevs  thank you for the info. We're reviewing this and we'll follow up with more details.

**Comment by aleksandrosadchiy** [comment]
do have the same issue on 2.4.4 Magento Cloud

**Comment by xaevik** [comment]
> do have the same issue on 2.4.4 Magento Cloud

Yes the same issue occurs on Magento Cloud as well.

**Comment by ibraheemnabeelfauzi** [comment]
Hello @aleksandrosadchiy  @xaevik  - we're yet to release compatibility with 2.4.4.4 - coming soon!

**Comment by wsajosh** [comment]
Thanks for your patience. We've released a new version which adds support for Magento 2.4.4 and PHP 8.1. Please go ahead and update
